# Generated by Django 5.0.3 on 2024-04-06 09:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_coursevideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideos',
            name='video_description',
            field=models.TextField(default=datetime.datetime(2024, 4, 6, 9, 5, 57, 958975, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='video_duration',
            field=models.TimeField(default=datetime.datetime(2024, 4, 6, 14, 36, 16, 935145)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='video_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
