# Generated by Django 5.0.3 on 2024-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideos',
            name='video_duration',
            field=models.DurationField(),
        ),
    ]
