# Generated by Django 5.0.3 on 2024-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coursevideos',
            name='video_duration',
            field=models.TimeField(),
        ),
    ]
