# Generated by Django 5.0.3 on 2024-04-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursevideos',
            name='video_duration',
        ),
    ]
