# Generated by Django 5.0.3 on 2024-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='coursevideos',
            name='video_duration',
            field=models.DurationField(null=True),
        ),
    ]
